### ISSUE TITLE
index error 

### ISSUE THREAD

**Issue by csh1205095339** [dorren002/HumanDetecting_HOG_SVM#2]
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    train_x = train[::,1:]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by csh1205095339** [comment]
> Traceback (most recent call last):
> File "train.py", line 66, in
> train_x = train[::,1:]
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

how to fix it
